version: '2.1'

services:
  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: postgis
      POSTGRES_DB: postgis
      POSTGRES_USER: postgis
    volumes:
      - ~/pg_data:/var/lib/postgresql/data
    ports:
      - 5435:5432  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgis"]
      interval: 10s
      timeout: 5s
      retries: 5
  message:
     image: "rabbitmq:3-management"
     ports: 
       - "5672:5672"
       - "15672:15672"
     healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 2s
      retries: 60
     
  servico_spring:
    build: servico_spring
    mem_limit: 512m
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgis
      - DB_PORT=5432
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ~/upload_dir:/upload
    depends_on:
      postgis:
        condition: service_healthy
      message:
        condition: service_healthy

  servico_dados:
    build: servico_dados
    mem_limit: 2048m
    environment:
      - DB_HOST=postgis
      - DB_PORT=5432
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ~/upload_dir:/upload
    depends_on:
      postgis:
        condition: service_healthy
      message:
        condition: service_healthy

  servico_otimizacao:
    build: servico_otimizacao
    mem_limit: 2048m
    environment:
      - DB_HOST=postgis
      - DB_PORT=5432
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ~/upload_dir:/upload      
    depends_on:
      postgis:
        condition: service_healthy
      message:
        condition: service_healthy        
