spring.application.name: servico_spring


servico_spring.upload.dir: /home/igor/upload_dir

server:
  port: 8082

spring.servlet.multipart.max-file-size: 250MB
spring.servlet.multipart.max-request-size: 250MB
server.tomcat.max-swallow-size: -1
server.tomcat.max-http-form-post-size: -1


spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:postgis}?stringtype=unspecified
    username: ${DB_USER:postgis}
    password: ${DB_PASSWORD:postgis}
  sql.init.mode: never
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    # This should no longer be needed with Hibernate 6
    #database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    show-sql: true
    database: postgresql
    # PotGIS configuration
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          lob:
            non_contextual_creation: true
        order_inserts: true
        order_updates: true
        generate_statistics: false
        
    defer-datasource-initialization: true

    

springdoc:
  api-docs:
    path: /api-doc/docs
  swagger-ui:
    path: /api-doc/swagger.html
            
logging:
  level:
    org:
      springframework:
        security: DEBUG
        
spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.dados-out-0:
    destination: msg_dados
  bindings.dados-out-1:
    destination: msg_otimizacao
  bindings.dados-out-2:
    destination: msg_demanda    
  
spring.rabbitmq:
  host: ${MESSAGE_HOST:localhost}
  port: 5672
  username: guest
  password: guest
---
spring.config.activate.on-profile: docker
server.port: 8080
spring.rabbitmq:
  host: message

servico_spring.upload.dir: /upload


            
            