insert into especialidade (nome) values ('Acupuntura');
insert into especialidade (nome) values ('Alergia e imunologia');
insert into especialidade (nome) values ('Anestesiologia');
insert into especialidade (nome) values ('Angiologia');
insert into especialidade (nome) values ('Cardiologia');
insert into especialidade (nome) values ('Cirurgia cardiovascular');
insert into especialidade (nome) values ('Cirurgia da mão');
insert into especialidade (nome) values ('Cirurgia de cabeça e pescoço');
insert into especialidade (nome) values ('Cirurgia do aparelho digestivo');
insert into especialidade (nome) values ('Cirurgia geral');
insert into especialidade (nome) values ('Cirurgia oncológica');
insert into especialidade (nome) values ('Cirurgia pediátrica');
insert into especialidade (nome) values ('Cirurgia plástica');
insert into especialidade (nome) values ('Cirurgia torácica');
insert into especialidade (nome) values ('Cirurgia vascular');
insert into especialidade (nome) values ('Clínica médica');
insert into especialidade (nome) values ('Coloproctologia');
insert into especialidade (nome) values ('Dermatologia');
insert into especialidade (nome) values ('Endocrinologia e metabologia');
insert into especialidade (nome) values ('Endoscopia');
insert into especialidade (nome) values ('Gastroenterologia');
insert into especialidade (nome) values ('Genética médica');
insert into especialidade (nome) values ('Geriatria');
insert into especialidade (nome) values ('Ginecologia e obstetrícia');
insert into especialidade (nome) values ('Hematologia e hemoterapia');
insert into especialidade (nome) values ('Homeopatia');
insert into especialidade (nome) values ('Infectologia');
insert into especialidade (nome) values ('Mastologia');
insert into especialidade (nome) values ('Medicina de emergência');
insert into especialidade (nome) values ('Medicina de família e comunidade');
insert into especialidade (nome) values ('Medicina do trabalho');
insert into especialidade (nome) values ('Medicina do tráfego');
insert into especialidade (nome) values ('Medicina esportiva');
insert into especialidade (nome) values ('Medicina física e reabilitação');
insert into especialidade (nome) values ('Medicina intensiva');
insert into especialidade (nome) values ('Medicina legal e perícia médica');
insert into especialidade (nome) values ('Medicina nuclear');
insert into especialidade (nome) values ('Medicina preventiva e social');
insert into especialidade (nome) values ('Nefrologia');
insert into especialidade (nome) values ('Neurocirurgia');
insert into especialidade (nome) values ('Neurologia');
insert into especialidade (nome) values ('Nutrologia');
insert into especialidade (nome) values ('Oftalmologia');
insert into especialidade (nome) values ('Oncologia clínica');
insert into especialidade (nome) values ('Ortopedia e traumatologia');
insert into especialidade (nome) values ('Otorrinolaringologia');
insert into especialidade (nome) values ('Patologia');
insert into especialidade (nome) values ('Patologia clínica/medicina laboratorial');
insert into especialidade (nome) values ('Pediatria');
insert into especialidade (nome) values ('Pneumologia');
insert into especialidade (nome) values ('Psiquiatria');
insert into especialidade (nome) values ('Radiologia e diagnóstico por imagem');
insert into especialidade (nome) values ('Radioterapia');
insert into especialidade (nome) values ('Reumatologia');
insert into especialidade (nome) values ('Urologia');